### ISSUE TITLE
command line option to update the cache

### ISSUE THREAD

**Issue by wofwofwof** [cboxdoerfer/fsearch#103]
Hello, 
I really love fsearch. There is currently one feature I've missing. I'd like to run update the index with cron and need an option like

  fsearch --update-index

that updates the index in the background.

cheers

wof

**Comment by cboxdoerfer** [comment]
Yes, it's kind of disappointing that a proper command line interface is still missing. Hopefully I can add that soon. 👍

**Comment by apapapapapapap** [comment]
Hi,

that's exactly what i'm desperatly looking for also. Fsearch is nearly perfect (at least for me),
only that there's no option for an automatic database-update.

I tried to call fsearch by command-line and let it update it's database, then
kill it (i.e. 'killall fsearch'). But it seems that the newly created database will
not be written then.

Aside from that: best search-prg on linux. period.
(I was using locate32 on windows before - always looking for something similar on linux)

greetings

**Comment by hi2u** [comment]
@cboxdoerfer   Would it be easier for you to add an `--update-index` flag that still causes the main GUI window to open?  That would be fine with me.  Obviously better if it can be purely in the background, but this would be a good compromise for now for many of us. 

I found myself using "Everything" on Windows about 20 times a day, but rarely using Fsearch unfortunately because I don't want to wait for the database to reindex every time (2+ million files).

If I could have a nightly cron job that lets it re-index that would be great, and I can just close the Window when I get up each day, or maybe just kill it with a script 10 minutes later or something.

**Comment by apapapapapapap** [comment]
That would be ok for me.

Anything so i can run a update by crontab
without manual interaction.

regards

**Comment by ffsedd** [comment]
I would appreciate this feature too. 

As a workaround I tried to update db via bash script, it seems to work fine. It has to kill running fsearch process though.

```
#!/usr/bin/env bash

#kill if running
pkill fsearch

# enable startup update
conf=$HOME/.config/fsearch/fsearch.conf
sed -i 's/update_database_on_launch=false/update_database_on_launch=true/' $conf

# run update, watch stdout
command="fsearch"
log="$HOME/.config/fsearch/update.log"
match="update_database"

rm -f $log
stdbuf -oL $command > "$log"  &
pid=$!

while sleep 1
do
    if fgrep --quiet "$match" "$log"
    then
        sleep 1
        kill $pid
        # disable startup update
        sed -i 's/update_database_on_launch=true/update_database_on_launch=false/' $conf
        exit 0
    fi
done
```

**Comment by jensenr30** [comment]
This feature would be really useful to me as well.
p.s.
Thanks for making such a great free and open source indexing search tool!

**Comment by TheConsciousness** [comment]
Any word on making a command line interface?

**Comment by cs96and** [comment]
#166

**Comment by cboxdoerfer** [comment]
This works now.
