### ISSUE TITLE
indexing files is slow

### ISSUE THREAD

**Issue by mehhrad** [cboxdoerfer/fsearch#115]
in comparison with Everything, Fserach is too much slower

Everything indexed my whole 2T hard drive within 1 minute(in windows); but Fsearch take more than 5 minutes.

Everything's database is also RealTime ... when i create new files in my hard drive ... it detects those files and add em to database immediately. it would be great if you add such feature to Fsearch.

btw thanks a lot for you great project.it makes my life easier :+1:

**Comment by cboxdoerfer** [comment]
> Everything indexed my whole 2T hard drive within 1 minute(in windows); but Fsearch take more than 5 minutes.

That's because Everything parses the MFT (Master File Table) of the NTFS file system which is much faster than traversing the file system to scan all items. However the most common file systems on Linux (ext4, xfs, btrfs, ...) don't have anything like a MFT, so there's nothing I can do about that.

There are a few things I can try to get slightly better indexing performance, but Everything will always be faster at indexing.

> Everything's database is also RealTime ... when i create new files in my hard drive ... it detects those files and add em to database immediately. it would be great if you add such feature to Fsearch.

Again that's because of another unique feature of the NTFS file system. Everything uses the USN Journal to detect new or modified files/folders. On Linux the only suitable option to detect those changes is inotify, however it doesn't work well if you want to monitor a huge file system with millions of files. inotify support is already on my todo, see #26.

**Comment by nazar2sfive** [comment]
I want my newly created files to appear on Fsearch automatically . I want some background indexing going on like everything.

https://github.com/albertlauncher/albert/issues/173

**Comment by cboxdoerfer** [comment]
> I was wondering, couldn't the NTFS drives have their MFT read by fsearch?

Sorry for the late response. Yes, that's possible, but I'm not going to implement that. It requires quite some work and since NTFS is a second class citizen on Linux and I'm also not using it, I'd rather work on other aspects.
