### ISSUE TITLE
Doesn't seem to respect default applications?

### ISSUE THREAD

**Issue by rieje** [cboxdoerfer/fsearch#135]
I may be mistaken, but fsearch seems like it doesn't respect default applications for whatever reason. On the pcmanfm file manager, opening a particular mkv file opens with mpv as desired. On fsearch, opening the same mkv file attempts to open with Firefox, and Firefox cannot actually play the file. If I select to open with mpv, then it will open with mpv appropriately, but I need it to open with mpv by default.

P.S. If you don't mind me asking, how's the progress on fsearch? It hasn't been updated for a while now and there are some crucial features lacking (e.g. renaming files, cut (move) files, improvement to the UI (resizing columns is funky) and specifying location of database (it would be great to have this on a tmpfs for performance reasons)). It would be a true replacement to Everything for Windows if these are possible. Regardless, respect to your efforts for bringing something similar to Linux.

**Comment by cboxdoerfer** [comment]
I have no idea how pcmanfm determines the default application to be used but FSearch uses xdg-open to open files. You can query the default file handler with `xdg-mime query default video/x-matroska`.

If this shows Firefox you should be able to fix that with `xdg-mime default mpv.desktop video/x-matroska`. Hope that helps.

> P.S. If you don't mind me asking, how's the progress on fsearch? It hasn't been updated for a while now and there are some crucial features lacking (e.g. renaming files, cut (move) files, improvement to the UI (resizing columns is funky) and specifying location of database (it would be great to have this on a tmpfs for performance reasons)).

Yes, unfortunately development really slowed down. It's basically the typical reasons which make it difficult for me to find any spare time to work on FSearch: family, work and friends.

However I still work on it whenever I find the time, so here is a short summary of what the last couple of months involved:

What I consider the most important thing right now is making FSearch more modular. So I did a lot of experimenting and evaluting what might be the best way to go forward and I came up with the following rather simple solution:

* libfsearch: This basically implements stuff like the core database functionality and performing queries on it
* fsearch_update_db: This is a small command line utility which walks the filesystem tree and uses libfsearch to generate database files. This becomes really useful when combined with tools like cron to schedule database updates
* fsearch_gtk/qt/ncurses: Those are just UI frontends which use libfsearch to do all the heavy lifting. I'm probably sticking with the GTK+ one by default for now, however it's kind of annyoing that a lot of development time in the past went into fighting GTK+ instead of actually improving the software.

Well, then I spent quite a lot of time to figure out how to implement that architecture, most importantly: Is libfsearch going to be written in C or something else? Rust quickly came to my mind as a possible alternative and I spent quite a lot of time working with it, but in the end C just made more sense to me and that's what I went with.

And that's basically the current situation of FSearch: I'm spending most of my very limited spare time on libfsearch, the CLI database update tool, optimizing the database format and basically building a solid foundation to build upon in the future (for me or others). Once that is done I'm going to update the UI frontend to those changes and prepare a release. All this work however involves some breaking changes, that's why I didn't do a stable FSearch release so far.

**Comment by cboxdoerfer** [comment]
I need to evaluate that. This seems to be a delicate issue since I first used some glib convenience api to launch applications, but that caused issues in KDE environments.

If it turns out there isn't just one solution that just works, I'll probably make that configurable. Then users can decide on their own if they want to use xdg-open, gio open, exo-open, ...

**Comment by blueray453** [comment]
Can you please at least implement **renaming files** & **cut (move) files**. 
I was a heavy "Search Everything" user and only lack of these two features make me sort of uncomfortable in my workstation.

**Comment by veksha** [comment]
If you look inside xdg-open script you will understand that it just detects your environment in **detectDE()** method and then launches the appropriate tool like _gio open, exo-open,_ etc...
your environment variable XDG_CURRENT_DESKTOP is not set to LXDE or something else, so it falls back to **open_generic()** method. that is why it tries firefox (it is hardcoded there).
