### ISSUE TITLE
Image and video thumbnails in results

### ISSUE THREAD

**Issue by Vioner** [cboxdoerfer/fsearch#140]
Are you planning to add media thumbnails to the search results?
Maybe as a toggleable option?

It'd be very useful.

Great work!

**Comment by cboxdoerfer** [comment]
Not as a core feature of fsearch. However I might add a small plugin API in the future, which I think is the proper place for such a feature.

**Comment by AnnanFay** [comment]
Can you explain in more detail why thumbnails are not a core feature of fsearch?

I'm looking for a linux alternative to Everything and this software comes up quite highly. However most of my searching is for images and being able to visually filter search results is a necessity. I have many thousands of generated images, after searching by filename I get a few hundred and pick out the visually interesting ones to examine.

**Comment by cboxdoerfer** [comment]
1. It's a lot of code, much more than FSearch has right now

2. I don't have the time nor interest to write and maintain that code

3. Plugins are more flexible at covering the huge variey of different file formats. If someone wanted thumbnails for some esoteric file format they just need to install a plugin instead of hoping that I care to add support for that file format to the core.

4. Thumbnails are a security risk, since they require decoding potentially malicious files, and doing them right isn't simple. With plugins users can opt in to the risk if they choose to.

**Comment by danielkrajnik** [comment]
It would be a useful feature. I thought about trying everything over wine, but sadly thumbnails don't work there neither (I assume for similar reasons).

My current workaround is to start up a windows virtual machine with network isolated to the host and run everything from there. It's a lot of steps, but sometimes this feature is necessary when you're working in more graphical environment.
