### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by jgjimenez** [cboxdoerfer/fsearch#15]
Greetings from Venezuela.

I would love to provide the translation into Spanish of your application.

**Comment by cboxdoerfer** [comment]
Thx, I'm currently in the process of setting up the translation system so others can contribute easily. I'll let you know when it's ready - should be the next couple of days.

**Comment by jgjimenez** [comment]
Thx Friend

**Comment by pavelmc** [comment]
I have the es.po completed, I'm tweaking it for layout, etc.  I'm folking now and make pull request in a few hours.

@jgjimenez took me, the initiative but I don't lose anything by trying...

Nice project, I was waiting for it, greetings from Cuba.

**Comment by cboxdoerfer** [comment]
@pavelmc, thx 👍

**Comment by cboxdoerfer** [comment]
Since the initial spanish translation has been added I think we can close this issue.

Btw: A couple of days ago I sent a request to https://weblate.org for free hosting - no answer yet. This would make managing the translations much easier. If this request isn't granted, I'm probably going to have a look at Transifex etc.
