### ISSUE TITLE
Regex to match beginning doesn't work

### ISSUE THREAD

**Issue by xPea** [cboxdoerfer/fsearch#155]
First of all: thank you very much for offering this software. It is great!

I think the regex beginning syntax `^` doesn't work. I try to find all files starting with `123` while using `^123` in the search bar, but I do not find any results, although I know that I got many files starting with `123`:  `123.txt$` results a file `123.txt`.

**Comment by cboxdoerfer** [comment]
I can't confirm that. Are you sure you have regex search enabled? By default the search only supports wild card patterns, regex needs to be enabled explicitly (`Search -> Enable RegEx` or `Ctrl+r`)

**Comment by leocaprio** [comment]
Thanks for answering. Have no access to my old account.

I still have the issue. Regex is enabled (checked). I have a file *helloWorld.html*, which I can see when I enter *helloWorld.html* in the search field. Now when I add the symbol *^* before it so that in the search field the string *^helloWorld.html* is set, I can't see any results.

I just saw that the version under Help->About is "UNKNOWN". Could this be the issue?

**Comment by cboxdoerfer** [comment]
Thanks, I'm glad you figured it out and it works now for you. :+1:
