### ISSUE TITLE
Need some guidelines

### ISSUE THREAD

**Issue by blueray453** [cboxdoerfer/fsearch#158]
I want to implement FSearch with some extra more features in **golang** specially for **Linux Mint Cinnamon**. To do that I will need some guidelines from the FSearch team. I tried to read the source code, but for me C seems difficult.

1. How does FSearch index all the files so fast in Linux? If I try to go through a small directory recursively to get the addresses and size of the files and subdirectories, I think it will take much longer. Is it concurrency or something more is into it.
2. What is the best method to constantly monitor file system change in Linux. I want to index once and after that only monitor cut-paste, delete etc. and update the database automatically.
3. Which database are you using to store the index. Which database do you suggest I use? What is the schema of the database?
4. I could drag files out of the window into a folder (in **Nemo, Linux Mint file manager**) or into a download box in my browsers. How do you suggest I do it?
5. `Right Click > Open in file Manager` should highlight that entry in the file manager (Nemo)
6. Is there anything I should know before starting this project? What would you change if you could start this project from scratch? What was the most difficult part in this project?

For beginning the project I think this would be enough. I might get back to you after I hit these milestones.

Thanks

**Comment by chg-hou** [comment]
@blueray453 

>  2. What is the best method to constantly monitor file system change in Linux. I want to index once and after that only monitor cut-paste, delete etc. and update the database automatically.

Maybe I could answer your second question. I did not find any elegant way to monitor the **whole** filesystem in Linux. Unlike NTFS where USN Journal is available for monitoring file changes continuously, ext4/ext3 has no such change journal. 
1. You may monitor limited numbers of files with inotify, which has a wrapper in golang ([https://github.com/fsnotify/fsnotify](https://github.com/fsnotify/fsnotify)). 
2. Or you may use fanotify. Currently, only a limited set of events is supported by fanotify. Unfortunately, create, delete, and move events, which you require, are not in the support list.

Please try the fsnotify project to see whether it could meet your requirement.

**Comment by blueray453** [comment]
> Unlike NTFS where USN Journal is available for monitoring file changes continuously

This was a very important piece of information. I dug a little deeper and [found](https://stackoverflow.com/questions/19645723/is-there-something-like-usn-journal-on-linux-filesystem)

> An program on Linux can do the same by using inotify. It allows a program to be notified about every change to the files.
> 
> It is not a function of any particular filesystem, but of the kernel's filesystem layer, so it works with any filesystem.
> 

Thank you very much for directing me towards **fsnotify**.

**Comment by phil294** [comment]
I dont have an answer to your questions, but why not contribute to fsearch instead? :-/ Is it only because it is written in C? (understandable)

**Comment by bernd-wechner** [comment]
> 
> 
> I dont have an answer to your questions, but why not contribute to fsearch instead? :-/ Is it only because it is written in C? (understandable)

I hear you. If all the endless effort that went into re-implementing stuff went into working together to improve stuff I can only imagine where we'd be today ... (way way ahead of where we are!).

**Comment by cboxdoerfer** [comment]
> How does FSearch index all the files so fast in Linux? If I try to go through a small directory recursively to get the addresses and size of the files and subdirectories, I think it will take much longer. Is it concurrency or something more is into it.

No concurrency, just a straight forward crawling through the sub directories: https://github.com/cboxdoerfer/fsearch/blob/master/src/database.c#L392

> What is the best method to constantly monitor file system change in Linux. I want to index once and after that only monitor cut-paste, delete etc. and update the database automatically.

inotify is currently your best option, but it has a couple of issues when you're trying to monitor huge directory trees: http://man7.org/linux/man-pages/man7/inotify.7.html#NOTES

However there seem to be some great changes to fanotify in upcoming kernel releases which might make that an even better alternative if you are fine requiring a 5.1 kernel.

> Which database are you using to store the index. Which database do you suggest I use? What is the schema of the database?

The database file format is a straight forward deserialization of the BTree which holds all the file/dir entries: https://github.com/cboxdoerfer/fsearch/blob/master/src/database.c#L236

So it's a custom format and what database you want to use highly depends on what you want exactly. Fast read speeds? Fast write speeds? Flexiblity? Incremental updates? ...

> I could drag files out of the window into a folder (in Nemo, Linux Mint file manager) or into a download box in my browsers. How do you suggest I do it?

I'm not exactly sure what it is you want me to answer here? The implementation obviously depends on the toolkit you want to use or if you want to use a custom toolkit you need to read the X11/Wayland documentation how to implement drag and drop functionality.

> Right Click > Open in file Manager should highlight that entry in the file manager (Nemo)

I don't know if Nemo supports that. If it does it's probably documented in its man page.

> Is there anything I should know before starting this project? What would you change if you could start this project from scratch?

I probably wouldn't use GTK anymore, but then again I also don't know what to use instead and if I had used something like Qt from the beginning I'd probably say that I wouldn't use Qt anymore. UI toolkits are complicated and you'll likely run into issues in whichever one you choose.

Maybe I'd also use Rust instead of C.

> What was the most difficult part in this project?

Nothing really, the most annoying part was making the GTK code fast enough. But other than that there weren't many difficulties. All the data structures, hot code paths, ... are quite straight forward and follow just a few rules: avoid memory allocations when possible, make use of cache friendly data structures in performance critical code paths, don't block the UI.

**Comment by blueray453** [comment]
@cboxdoerfer I can not thank you enough for this detailed guideline. Thank you very much.
