### ISSUE TITLE
"Enable dark theme" doesn't work

### ISSUE THREAD

**Issue by mimf** [cboxdoerfer/fsearch#16]
In preferences, there's an option to "enable dark theme". I've enabled that, restarted fsearch and nothing changed..

OS: Ubuntu 16.04

**Comment by cboxdoerfer** [comment]
Some GTK themes don't provide a dark variant, I think Ubuntu's Ambiance theme is one of them. Maybe you are using such a theme? If that's the case there's very little I can do to fix it, other than add a note in the preference dialog that this option might not have an effect, depending on the current GTK+ theme.

**Comment by ronjouch** [comment]
> Some GTK themes don't provide a dark variant, I think Ubuntu's Ambiance theme is one of them. Maybe you are using such a theme? If that's the case there's very little I can do to fix it, other than add a note in the preference dialog that this option might not have an effect, depending on the current GTK+ theme.

Yes, same here, using default Ambiance theme under Ubuntu 16.04.1LTS

**Comment by mimf** [comment]
I'm on Xubuntu 16.04 (not Ubuntu as I said in the OP) and my theme is the default one.

**Comment by cboxdoerfer** [comment]
@mimf, yes Xubuntus default theme (Greybird) doesn't provide a dark theme either. So FSearch can't do anything about that.

Here's the bug report from the Greybird project: https://github.com/shimmerproject/Greybird/issues/37

Now in order to fix this you either have to find a theme which provides both dark and light versions (e.g. Adwaita, Elementary or Arc) or you might want to help the Greybird guys to add a dark version to their theme.

To make users aware of that, I'll add a note in the preferences dialog. See #33
