### ISSUE TITLE
How to Track Latest Changes

### ISSUE THREAD

**Issue by blueray453** [cboxdoerfer/fsearch#176]
Today I got an update. Its version says `UNKNOWN`.

I am using:
```

sudo add-apt-repository ppa:christian-boxdoerfer/fsearch-daily
sudo apt-get update
sudo apt install fsearch-trunk
```

I was interested to know what the newly added features are, so I checked https://github.com/cboxdoerfer/fsearch/releases

I think the link has not been updated for some time.

I also checked https://github.com/cboxdoerfer/fsearch/wiki/Roadmap for tick marks. I could not figure out.

How can I track changes and know what new features has been added?

**Comment by cboxdoerfer** [comment]
You're subscribed to the daily builds, i.e. those are built every day, if there was some code change. For the update you got on that day, that was caused because some translations have been updated.

The releases page has nothing to do with the development versions you are using, therefore you won't find any changelog for your build there. You need to look at the git commit log.

As for the `UNKOWN` version string, I'll look into that. We should probably display something like `$MAJOR.$MINOR-$COMMITID`.

**Comment by cboxdoerfer** [comment]
I just fixed the `UNKOWN` version string.
