### ISSUE TITLE
fsearch does not close immediately

### ISSUE THREAD

**Issue by AtilioA** [cboxdoerfer/fsearch#194]
Don't know how to make it reproducible, but I'm on Linux Mint 20 Cinnamon. I've tested it with multiple settings to no avail. This does not happen with any of my other programs.
If the program is updating its database, ALT+F4 closes it immediately but not otherwise. Killing it through the system monitor or terminal (both doing basically the same thing) closes it immediately. This was already happening before the recent updates.

<img src="https://user-images.githubusercontent.com/27153776/88487094-a0cbbd80-cf58-11ea-89ca-7664f9b1d97f.gif" alt="drawing" width="66%"/>

Sometimes it will even crash when trying to exit (_"is not responding"_ dialog opens up):

<img src="https://user-images.githubusercontent.com/27153776/88487091-9c070980-cf58-11ea-8816-6c65e60928df.gif" alt="drawing" width="66%"/>

I'll update this if I find out anything.

**Comment by cboxdoerfer** [comment]
Thx for reporting. The reason why it doesn't close immediately is because FSearch saved the database on disk when you closed it. However, just a couple of hours ago I fixed that and closing should now be instantly.

Keep in mind that it might take a day or so until the package in the PPA gets updated. So you should receive the update soon if you use the PPA.

Please let me know if the issue is resolved then.

**Comment by AtilioA** [comment]
I've built from source (c72fb6959705d887a0d4a1423d3a0a38d2c4cdd1) since the PPA still got a broken version (FSearch crashing when typing). This has been fixed on my end 👍.
