### ISSUE TITLE
Option to make it into a launcher layout like Synapse

### ISSUE THREAD

**Issue by marksev1** [cboxdoerfer/fsearch#20]
An option to shrink the UI into a launcher style app and also the appropriate behaviour of such a launcher app.

**Comment by marksev1** [comment]
What do you think cboxdoerfer?

**Comment by cboxdoerfer** [comment]
That depends on what you expect of a launcher app?

**Comment by marksev1** [comment]
That it comes up instantaneously after a certain key combo (so its running in the background) and that its visually nice and small like Albert or Mutate launcher. And that it gives you suggestions then bellow for either launching an app or opening a document or play a video and so forth.

**Comment by bozicschucky** [comment]
I also prefer the launcher style like synapse tho synapse is not accurate when searching for some files and i think this fsearch can solve this.

**Comment by cboxdoerfer** [comment]
> That it comes up instantaneously after a certain key combo (so its running in the background)

You can already do that. Hitting <ESC> hides the FSearch window, and you can bind any key combination to focus the window again.

> that its visually nice and small like Albert or Mutate launcher

Well, you can already hide much of the interface elements (statusbar, menubar, columns, search button,  etc.) and remember a certain window size during sessions. Going further by providing a launcher UI style isn't something I'm interested in, because I already use Albert and I'm pretty happy with it as a launcher.

However, once the backend library for searching and database management is ready, people can implement any kind of frontend (CLI, ncurses, launcher style, ...) for FSearch.

**Comment by mimf** [comment]
> You can already do that. Hitting ESC hides the FSearch window, and you can bind any key combination to focus the window again.

Well, that's not really the behaviour he wants. Take a look at "Albert". It's an omnilauncher. It hides (no window) unless we call it. Also, the results window is non-existent, unless we search for something. Its size is a function of the number of results we have.

**Comment by cboxdoerfer** [comment]
> Well, that's not really the behaviour he wants. Take a look at "Albert". It's an omnilauncher. It hides (no window) unless we call it.

Well that's easy to fix, I can add an option to hide the window once it loses focus.

> Also, the results window is non-existent, unless we search for something. Its size is a function of the number of results we have.

If it is possible to do that easily with GTK+ (I'm not sure if window resizes correctly), I can add an option for that too, but I won't add any hacks for that. Because I don't have any interest to compete with Albert, Synapse, etc.

Anyway, this is something for future versions (maybe 0.2).

**Comment by dzackgarza** [comment]
Out of curiosity, would it be feasible for fsearch to provide an API or executable that something like Albert could hook into in the future? This seems like it'd make a fantastic replacement for the "omnisearch" bar built into the Windows 10 start menu (for example).

**Comment by cboxdoerfer** [comment]
@dzackgarza, yes that's my plan. I currently doing some work to split FSearch into two projects, libfsearch (with an API for managing the database and performing queries) and fsearch-gtk (which builds upon libfsearch and just adds a nice frontend).

**Comment by cboxdoerfer** [comment]
This should work now.
