### ISSUE TITLE
Accented characters in search produce no result

### ISSUE THREAD

**Issue by ngirard** [cboxdoerfer/fsearch#217]
(Just tested Fsearch for the first time... kudos for this project !)

Using latest .deb package from Ubuntu ppa.

Steps to reproduce:
1. In a folder <d> indexed by Fsearch:
    `mkdir <d>/Test_accented && cd <d>/Test_accented`
    `touch test_{à,á,â,ã,ä,å,æ,ç,è,é,ê,ë}.txt`
2. Update Fsearch's database
3. Search for e.g. `test_à`

Expected:
Newly created files should appear in search results

Observed:
None of the newly created files appear in search results

This is a major, blocking defect for me.

Cheers!

**Comment by cboxdoerfer** [comment]
Hi, thanks for reporting! This should now work. The PPA will be updated in one or two days with the fixed versions.

**Comment by cboxdoerfer** [comment]
I forgot to mention that search performance will be worse with those accented characters in case-insensitve mode, because they will trigger rather slow utf8 string conversions. This will be fixed as well soon.

**Comment by ngirard** [comment]
Thanks for the quick fix !
Would you be kind enough to point me to building instructions for Debian-based distros, e.g. the building instructions for your PPA's packages ?

**Comment by ngirard** [comment]
> I forgot to mention that search performance will be worse with those accented characters in case-insensitve mode, because they will trigger rather slow utf8 string conversions.

Did you consider leveraging Rust for the core of your project ? Because Rust's regex support with utf8 is [first-class](https://github.com/rust-lang/regex).

Also, I happen to have authored a [project in Rust](https://github.com/ngirard/lolcate-rs) whose spirit is similar to yours (although the feature sets don't fully match), but written for the command-line. As I understand, you're considering changing your database format. Could there be an opportunity here for us to bring our stuff together ?

**Comment by cboxdoerfer** [comment]
Do you want to create a .deb package or do you just want to try a local build?

The basic build instructions can be found here: https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions

Making a debian package is a little more complicated and I would need to do some research on my own to figure out again how it works.

**Comment by ngirard** [comment]
A local build will be just fine until the next PPA build, thank you very much !

**Comment by cboxdoerfer** [comment]
> Did you consider leveraging Rust for the core of your project ? Because Rust's regex support with utf8 is first-class.

Yes, I did. I even played around with it a bit in the beginning and it's been on my mind ever since to use it instead of C. But a lack of time and much better familiarity with C caused me to stick with C so far.

> Also, I happen to have authored a project in Rust whose spirit is similar to yours (although the feature sets don't fully match), but written for the command-line. 

That project looks nice! I'm definitely going to try it out.

> As I understand, you're considering changing your database format. Could there be an opportunity here for us to bring our stuff together ?

Yes, that's my plan and yes that might be a interesting idea. This would also make a transition to Rust much easier, because we could use one implementation of the database. What requirements do you have for the database?

**Comment by ngirard** [comment]
These are neat instructions, I've got it up and running and it's working fine. Usability-wise it's just great ! Seems like you put some more efforts into the gui recently and it did pay off. Congrats and thank you !

> What requirements do you have for the database?

What do you mean by requirements ?

**Comment by cboxdoerfer** [comment]
> These are neat instructions, I've got it up and running and it's working fine. Usability-wise it's just great ! Seems like you put some more efforts into the gui recently and it did pay off. Congrats and thank you !

Great  and thanks :)

> What do you mean by requirements ?

Things like what sort of data it needs to store (e.g. file name, size, modification time, ...), how are the priorities in terms of read/write performance, does it have to be human readable, does file size matter, is incremental update support needed, ...

My goals are something like:

* read performance is much more important than write performance
* the database is read fully to RAM, so no support for partial reads of certain data elements is required
* in order to improve sort performance the database should also be able to store the sort order for all fields (name, size, path, ...)
* human readability is not required because it'll likely hurt performance
