### ISSUE TITLE
Database update is time-consuming each time after fsearch is started.

### ISSUE THREAD

**Issue by hongyi-zhao** [cboxdoerfer/fsearch#233]
Hi,

With the option *Update database on start* enabled, it's a very time-consuming job for databse updating each time after fsearch is started. It seems that the update operation is not incremental. I want to know whether this operation can be further sped up / optimized?

Regards,
HY

**Comment by cboxdoerfer** [comment]
There's likely room for improvement and optimizations. For example on SSDs it might be useful to use multi-theaded scanning.

You can also perform the update before FSearch was started if that's useful in your use case, with the command line flag.

And yes, the update isn't incremental. I'm not sure if this would speed things up, because the most time is spent on traversing the filesystem, which needs to be done with incremental updates as well.

But in general, the update will never be as fast as Everything with NTFS drives, because Linux file systems don't have something like the MFT and an USN journal.

**Comment by hongyi-zhao** [comment]
> There's likely room for improvement and optimizations. For example on SSDs it might be useful to use multi-theaded scanning. But that hasn't been implemented.

Thanks for this explanation.

> 
> You can also perform the update before FSearch was started if that's useful in your use case, with the command line flag.

When the number of files is huge, any way is time-consuming. Say, for my case, see following for more info:

```
werner@X10DAi-01:~$ time fsearch -u
Updating database... ^C

real	4m11.845s
user	0m3.031s
sys	0m15.682s
```

I terminated it and 4m11.845s has been elapsed.

> 
> And yes, the update isn't incremental. I'm not sure if this would speed things up, because the most time is spent on traversing the filesystem, which needs to be done with incremental updates as well.

I really don't have experiences on the mechanism of this deep level.

> 
> But in general, the update will never be as fast as Everything with NTFS drives, because Linux file systems don't have something like the MFT and an USN journal.

Thanks for hints again.

**Comment by cboxdoerfer** [comment]
> When the number of files is huge, any way is time-consuming. Say, for my case, see following for more info:

That's quite a long time. How many files do you have and do you use an SSD or HDD?

But yes, the time to create the database depends highly on the number of files and the performance of the storage device.

One small optimization you can do manually, is to exclude certain folders from the update process. For example when you have a folder with many files that don't change often, like a music collection, you can uncheck the `Update` checkbox in the settings for that folder.

**Comment by hongyi-zhao** [comment]
> That's quite a long time. How many files do you have and do you use an SSD or HDD?

The info `2,975,350 items` is shown on the status line of fsearch.

I've 1 SSD (1T) + 1 HDD (2T).

> 
> But yes, the time to create the database depends highly on the number of files and the performance of the storage device.
> 
> One small optimization you can do manually, is to exclude certain folders from the update process. For example when you have a folder with many files that don't change often, like a music collection, you can uncheck the `Update` checkbox in the settings for that folder.

Do you mean the `Database --> Exclude` option?

**Comment by cboxdoerfer** [comment]
> Do you mean the Database --> Exclude option?

You can use that too, if there are any folders in particular where you don't want to search in at all. But what I was referring to is the `Update` column here:

![2020-10-29-110441_602x158_scrot](https://user-images.githubusercontent.com/6108388/97554194-b7116b80-19d6-11eb-8d5c-9c887f3f0688.png)

What this does is that when `Update` is unchecked FSearch will only load the folder from the database file, without scanning the folder again on each database update.

**Comment by hongyi-zhao** [comment]
Anyway, this is a compromise but not a perfect and efficient solution.

**Comment by cboxdoerfer** [comment]
Yes, and I fear that's the best we can do on Linux. There's no other way to get the up-to-date content of the filesystem on Linux than to traverse and scan the whole filesystem, which is a time consuming task since storage devices are usually pretty slow.

**Comment by hongyi-zhao** [comment]
1. Compared to [fzf](https://github.com/junegunn/fzf), which has higher performance?
2. IMHO, all operations need to be implemented in parallel / multi-core / multi-threaded mode, if possible.

**Comment by cboxdoerfer** [comment]
On my computer with ~3 million files it takes 98 seconds for fzf to populate all files and 109 seconds for FSearch to build its database, both with cold caches. So while I agree there's room for improvement I doesn't look like much -- especially considering that FSearch also indexes other data as well. What numbers do you get on your computer?

**Comment by hongyi-zhao** [comment]
> What numbers do you get on your computer?

Fzf is currently not installed on my box. So I can't give your concrete numbers/durations for them. But the fsearch, for my case, need at least 10 mins for initialization/updating of the database.

**Comment by cboxdoerfer** [comment]
Without concrete numbers and ways to reproduce it I don't think there's anything I can do to investigate this further.

**Comment by hongyi-zhao** [comment]
I think the root cause is the huge amount of files in my system. And if the Linux based file systems doesn't exist the similar characteristics on which fsearch can rely just as the windows Everything's situation, a revolutionary breakthrough in performance is impossible to achieve.

**Comment by cboxdoerfer** [comment]
Yes, for that many files you might be better of with tools who don't use a database approach, but populate their list on the fly. Finding every possible match with those will still take a similar amount of time, but they can report at least some results relatively quickly. AFAIK Catfish is one of those search utilities which does that.

**Comment by hongyi-zhao** [comment]
See the following info:

```
$ sudo apt-get install catfish 
[...]
Initializing mlocate database; this may take some time... 
```
So, this one is based on mlocate which I've used before.

**Comment by bigntallmike** [comment]
I'd think the "right" approach would be to have a service that uses inotify and updates the database in the background in real time when the filesystem is changed after the first run.  Alternatively, use inotify to queue up changes and actually do the database upgrades as an incremental change on the next startup of the software.

**Comment by cboxdoerfer** [comment]
> I'd think the "right" approach would be to have a service that uses inotify and updates the database in the background in real time when the filesystem is changed after the first run.

I already tried to use inotify and the experience sucked and with the number of files/folders we have to deal with in this issue (>1 million) it's basically unusable. It only works fine with relatively small directory trees, which also don't take long to scan anyway.

> Alternatively, use inotify to queue up changes and actually do the database upgrades as an incremental change on the next startup of the software.

Even if inotify worked well with such huge directory trees, both approaches would still require a full scan beforehand. This can't be avoided, because we need to know what files/folders are there to begin with and only then can we monitor them for changes. So you still need to wait whatever amount of time it takes to perform a full scan before you can use Fsearch with an up-to-date database.

**Comment by bigntallmike** [comment]
> Even if inotify worked well with such huge directory trees, both approaches would still require a full scan beforehand. This can't be avoided, because we need to know what files/folders are there to begin and only then can we install the inotify watches to monitor them for changes. So you still need to wait whatever amount of time it takes to perform a full scan (plus the time to install the inotify watches) before you can use Fsearch with an up-to-date database.

Granted, but I presume over time, people use fsearch more than once, and they don't modify N files between uses, where N is the size of the initial scan.
That said, I use cloud backup software that uses inotify for continuously backing up an entire fileserver without real performance issues -- so I know it /can/ be done with very large file sets.  I've just personally only coded for it with smaller situations myself so I can't speak to the 'how'.

**Comment by cboxdoerfer** [comment]
> Granted, but I presume over time, people use fsearch more than once, and they don't modify N files between uses, where N is the size of the initial scan.

No, but you can't avoid a full scan after each reboot of the computer and restart of the monitor service. That's the only way you can ensure the database is consistent with the data on the filesystem.

And even if this full scan can be avoided, the process of adding all the inotify watches requires a full directory tree traversal anyway. inotify requires you to add a watch on every folder you want to monitor, but in order to do that you need to find every folder in the directory tree and that's the most time consuming task and is exactly what slows down the database update. And if you want to know what folder an inotify event belongs to you also need to cache the whole folder structure, which is basically exactly what the database update does.

> That said, I use cloud backup software (crashplan by code42) that uses inotify for continuously backing up an entire fileserver without real performance issues -- so I know it /can/ be done with very large file sets. I've just personally only coded for it with smaller situations myself so I can't speak to the 'how'.

The major problem on desktops is that you can have multiple applications which use inotify extensively (file sync applications, audio players, launchers, photo managers, IDEs, ...) and thereby fight over the already small default limit of allowed inotify watches. I found that really annoying in my testing when suddenly other applications failed doing their tasks because FSearch was using a ridiculous amount of inotify watches. But maybe with proper documentation and a good UI this issue can be communicated well to the user.

**Comment by pavanyogi** [comment]
There might be scope for improvements in terms of usability. As of now, we can't use the fsearch when database scanning is in the progress. Once old fsearch db is built successfully, on the next restart we can move database scanning to background job and scan/make new fsearch-db file. In the meantime, fsearch can continue working with the help of the old fsearch-db file. Once new scanning completes and new fserach-db file is built successfully, we can point to new fearch-db and delete the old fsearch-db file. In this way, the fsearch application will not be blocked during the new scanning and db-make process.

**Comment by cboxdoerfer** [comment]
@pavanyogi, even now FSearch shouldn't block at all during scanning. The new database is built completely in the background, while you can simultaneously search and work with the files in the old database. Maybe your using an old build of FSearch?

**Comment by Lemm99** [comment]
> @pavanyogi, even now FSearch shouldn't block at all during scanning. 

That's not the case unfortunately. I'm using the daily PPA, kept up to date on my end. Linux mint 20.1. Around 1.5 Million files. FSearch says "Updating Database. This may take a while." Happens every time after reboot. Searching for any string yields no results during this scan.

**Comment by cboxdoerfer** [comment]
That's only supposed to happen when the database format changes, which only happened once so far and that was yesterday, when I pushed a new database format to increase performance in a couple of areas. If it happens after every restart that's either a bug in FSearch or a different issue somewhere else (e.g. when fsearch has no write permissions to save the database to disk).

So in order to get an initial overview of what's going on: Disable automatic database updates on launch in the settings, then update the database manually from the menu once. When that's finished restart and launch FSearch. Does searching now work?

*  If yes, update the database again manually, does searching still work while it's updating? 

* If no, then that means the database either couldn't be loaded or saved from/to disk and there's some larger issue going on

**Comment by pavanyogi** [comment]
I am using fsearch version 0.1beta4. In my case, the search is working while manual DB update is in the progress. I have one idea for further improvements. We can display some info like LAST-DB-UPDATED: N (sec/mins/hours/days/months) BEFORE etc. Based on this information the user can decide whether he needs to update the DB again or not. Also, we can run the DB update process via system cron job daily.

**Comment by cboxdoerfer** [comment]
> We can display some info like LAST-DB-UPDATED: N (sec/mins/hours/days/months) BEFORE etc. Based on this information the user can decide whether he needs to update the DB again or not.

Yes, that sounds like a good idea, I'll add that.

**Comment by Lemm99** [comment]
> That's only supposed to happen when the database format changes, which only happened once so far and that was yesterday, when I pushed a new database format to increase performance in a couple of areas.

That explains it. I purged fsearch to start fresh then reinstalled it and it works as you describe. I feel bad for anyone with millions of files that doesn't see this thread. It's such a great feature. Thanks a lot.
