### ISSUE TITLE
Add Flatpak package

### ISSUE THREAD

**Issue by aha999** [cboxdoerfer/fsearch#275]
**Is your feature request related to a problem? Please describe.**
Currently we can't download/install and update your software via app stores on Linux that use Flathub. 

**Describe the solution you'd like**
Add Flatpak packages and include them on Flathub for cross-Linux distribution.

**Additional context**
On a popular Pop!OS Linux that i use, Flathub is included by default, so most of the programs are searchable and updateable that way.

**Comment by CodeCubeNeo** [comment]
I would also really like to add this app to the flatpak repository, since I think it would raise its popularity, and also be easier for some users to install. It is really simple and it would help this app a lot, just a few steps: https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app. We would really appreciate it.

**Comment by cboxdoerfer** [comment]
Thanks for the reminder, I just submitted FSearch to flathub: https://github.com/flathub/flathub/pull/2790

**Comment by CodeCubeNeo** [comment]
Awesome!!!! Really appreciate it :). I guess it takes some time for flatpak to accept the package to the main repo? I cant find it yet on the flathub website?

**Comment by cboxdoerfer** [comment]
Yes, it still needs to get approved by the flathub maintainers. I'll update you when that's done and it can be downloaded from flathub.org

**Comment by cboxdoerfer** [comment]
It's now available on flathub: https://flathub.org/apps/details/io.github.cboxdoerfer.FSearch
