### ISSUE TITLE
Search inside files

### ISSUE THREAD

**Issue by simurq** [cboxdoerfer/fsearch#288]
It would be really nice to add this feature, compatible with Regex. Especially for searching for a specific word or phrase inside a multiple of TXT, DOCX, OTF files. Surprised that it's not been requested yet... But maybe you're planning to add this feature some time later along the path, didn't see it posted on the front page either.

Thanks!

**Comment by cboxdoerfer** [comment]
It's already been requested in #17. It's still not an important feature to me and won't happen anytime soon, except someone else implements it.

However the prerequisite of this feature would be an advanced query syntax, where you can type things like:

`*.txt $content(some interesting phrase)`

Because without being able to narrow down the files to be searched in first, it'll take ages to complete.

**Comment by simurq** [comment]
Ah, okay, thanks for the explanation. It's clear now. And please keep up the good work!

**Comment by Wallby** [comment]
> Also the prerequisite of this feature would be an advanced query syntax, where you can type things like:
> 
> `*.txt $content(some interesting phrase)`
> 
> Because without being able to narrow down the files to be searched in first, it would take ages to complete.

UltraSearch uses two text boxes instead, one for files and one for content..
![image](https://github.com/cboxdoerfer/fsearch/assets/13614975/108db8de-abf3-47a3-accb-e5c7f9c1f2c0)

**Comment by itsnotsaved** [comment]
@simurq https://sourceforge.net/projects/searchmonkey/
