### ISSUE TITLE
HElp! =)

### ISSUE THREAD

**Issue by Lecharge** [cboxdoerfer/fsearch#337]
Is IT possible to seatch ntf formated disks? if so how do i add them, gets premission denied

**Comment by cboxdoerfer** [comment]
Yes, you can search in any folder where you user has read permissions, including NTFS filesystems. If you get "permission denied" messages your user simply lacks read access to those drives, which means you need to fix the mount flags or change the permissions of the entries on the drive. Since I don't now how you mounted those drives and what the permissions look like, there's nothing I can help you with.

Closing, since it's not an issue caused (or fixable) by FSearch.
