### ISSUE TITLE
[BUG] libicuuc.so.XX cannot open share object [Solved}

### ISSUE THREAD

**Issue by nPHYN1T3** [cboxdoerfer/fsearch#349]
**Describe the bug**

fsearch: error while loading shared libraries: libicuuc.so.70: cannot open shared object file: No such file or directory

**To Reproduce**
Be one day after April 20th and launch fsearch ;p

**Expected behavior**
For the application to launch (or to find the current installed lib)

**Desktop (please complete the following information):**
 - OS: Garuda (Arch) Linux
 - AUR GIT build
 - fsearch-git 0.2alpha.r243.g5dc7cf8-1 (can't run fsearch --version because it won't run ;p)
 - Output of `localectl status`
      System Locale: LANG=en_US.UTF-8
       VC Keymap: us
      X11 Layout: us

**Additional context**
Worked yesterday. I read the other posts about fsearch and previous libicuuc issues so I rebuilt/reinstalled the libs and fsearch but fsearch still looks for 70 while the system is using 71.1-1.

[ SOLUTION ] This was a snake bite gotcha issue where in I had expected the AUR version to be building but since Pamac is kinda crap at denoting some things I hadn't noticed it was a packaged build and uninstalling and reinstalling was doing just that i.e. not rebuilding to reinstall. Switching to the -build required- version and building was/is the fix.

** Title Edit as per @ProtoFoo. Since this has happened a few times and there are reports for several libicuuc.so.XX versions I just went the Mega Man 20XX route.

**Comment by nPHYN1T3** [comment]
The manual build is simply the aur build (pamac) from where I also removed both before reinstalling. Given the lib isn't hard coded (didn't think it was) where is it looking to find the system default? The last two posts about this and rebuilding make it sound like indeed the build needs to update the to find it rather than a PATH or env variable.

**Comment by c02y** [comment]
I installed pre-built package version `fsearch-git 0.2alpha.r243.g5dc7cf8-1` from third party repo called `chaotic-aur`, it won't start:
```
$ fsearch
fsearch: error while loading shared libraries: libicuuc.so.70: cannot open shared object file: No such file or directory
```
But the version `fsearch-git-0.2alpha.r63.g54ab19c-1` installed from AUR is working fine.

**Comment by nPHYN1T3** [comment]
Yeah that is the issue. Comically the package was updated just a few days ago but then was obsolete almost immediately.

**Comment by cboxdoerfer** [comment]
@c02y yes, this means the package in the chaotic-aur is simply inconsistent with the official Arch repos and needs to be rebuilt by whomever maintains this repository. This whole rebuilding situation when dependencies get updated can't be avoided with the AUR, it's by design:

> The AUR is unsupported, so any packages you install are your responsibility to update, not pacman's. If packages in the official repositories are updated, you will need to rebuild any AUR packages that depend on those libraries.

In the case of Fsearch that's primarily the case whenever `icu` gets updated.

**Comment by ProtoFoo** [comment]
I had the exact same problem after doing some pacman updates on my Arch based distribution. Running `yay -S fsearch` did a recompile on my system and the problem was fixed. I am using the release version, not the git version.

@nPHYN1T3 would you care to edit the title to make it more descriptive? Suggestion:
> libicuuc.so.70: cannot open shared object file

This would help others finding this issue. Thanks!

@cboxdoerfer would a pacman hook that recompiles fsearch whenever icu gets updated be a useful solution? Maybe add an entry about this in the Wiki?
