### ISSUE TITLE
[BUG] Cannot select other disks when trying to Add a path to the Include list in database parameters

### ISSUE THREAD

**Issue by matt32106** [cboxdoerfer/fsearch#354]
**Describe the bug**
I want to add 2 other disks to the paths to search and when I click other location I don't see the drives.

**To Reproduce**
Select parameters, database, include
Click + to add a path, a selection window appears
Click "other locations"
There is a single line "Computer"
If I click "Computer" my 2 other disks /SSD1 and /Seagate2 are not in the list (screenshot below)

**Expected behavior**
List all disks and directories in the selection window

**Screenshots**
https://imgur.com/ih47czh.png

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 & kde plasma
 - How you installed FSearch: snap
 - Version: FSearch 0.1.2
 - Output of `localectl status`
```
System Locale: LANG=en_US.UTF-8
                  LC_NUMERIC=fr_FR.UTF-8
                  LC_TIME=fr_FR.UTF-8
                  LC_MONETARY=fr_FR.UTF-8
                  LC_PAPER=fr_FR.UTF-8
                  LC_NAME=fr_FR.UTF-8
                  LC_ADDRESS=fr_FR.UTF-8
                  LC_TELEPHONE=fr_FR.UTF-8
                  LC_MEASUREMENT=fr_FR.UTF-8
                  LC_IDENTIFICATION=fr_FR.UTF-8
       VC Keymap: n/a
      X11 Layout: fr
       X11 Model: pc105

```

**Additional context**
If I try to click any directory on the right hand side of the screenshot I get a "permission denied" error

**Comment by matt32106** [comment]
I removed the snap and installed from ppa and it works.

Snap breaks something that works once again.

**Comment by cboxdoerfer** [comment]
Yes, that's caused by the Snap runtime. Running `sudo snap connect fsearch:removable-media` might solve it, but some limitations can't be avoided with the Snap version. For example you can't find most hidden files and the "Open with" context menu doesn't work. So in general it's advised to use the PPA instead, which doesn't have any of those issues.

Unfortunately I'm not aware of anything I can do on my part to solve those issues with the Snap. If some users hadn't asked for a Snap version, I probably wouldn't have released it in the first place, due to all those annoying issues which only cause frustration with users and myself, when the application doesn't work as expected.
