### ISSUE TITLE
Add option to delete selected files

### ISSUE THREAD

**Issue by spsf64** [cboxdoerfer/fsearch#38]
Maybe even 2 options like "delete" (permanently) and "move to trash"
Thanks for this great project!

**Comment by cboxdoerfer** [comment]
Sure, I'll add those.

**Comment by spsf64** [comment]
Thanks, maybe other options like "copy to" and "move to" and select folder where to put such selected files would be a great addition?

**Comment by cboxdoerfer** [comment]
@spsf64, yes, copy and move to sound like useful additions. I'll add them. I opened a bug report for those: #48

**Comment by cboxdoerfer** [comment]
@spsf64  I just added the option to delete files and move them to trash. Currently the deleted files will still show up in the results (however the icon will indicate that they have been removed). But this will be fixed when I add file system monitoring.

**Comment by orschiro** [comment]
Wow, great. :-)

Can this also delete files outside the home directory?

**Comment by cboxdoerfer** [comment]
@orschiro, that depends on the permissions of the parent directory. If you have permission to modify it (write permission) you can delete files in there.

So in general you can't delete every file because usually your user can't modify everything. However I could use PolicyKit for example, then you get prompted for a password when you want to modify system files. I'll have a look how this can be done.

**Comment by spsf64** [comment]
@cboxdoerfer thanks! I will check this later today.
Any news on select/deselect paths in darabase?

**Comment by cboxdoerfer** [comment]
@spsf64, there's some progress on a prototype but it's nothing usable yet and I'm still not sure about some of the details. Maybe by the end of this month I'll be able to publish some of the progress.

The reason why this takes so long is because I need to implement a byte code compiler and interpreter for this to work nicely and efficiently.

**Comment by spsf64** [comment]
@cboxdoerfer Just checked and the option works perfectly!
Just a small suggestion, to delete a file shift+del instead of ctrl+del to comply with file manager standards?
Thanks for this great software!

**Comment by cboxdoerfer** [comment]
@spsf64, yes sure. Fixed it.

**Comment by spsf64** [comment]
Wow, this one was fassst! Thank you, have a nice weekend.

**Comment by cboxdoerfer** [comment]
@spsf64, np, you too. :)
