### ISSUE TITLE
Open files and folders with `open` on MacOS.

### ISSUE THREAD

**Issue by DUOLabs333** [cboxdoerfer/fsearch#410]
**Is your feature request related to a problem? Please describe.**
FSearch mostly works on MacOs with native gtk3 --- you can search, sort, etc. However, you can't open files/folders --- you get `Operation not supported for the current backend`. This is most likely because MacOS doesn't have desktop files.

**Describe the solution you'd like**
Add a special case for MacOS (probably as a preprocessor macro) that hardcodes `/usr/bin/open` as the command to open files (`folder_open_cmd` doesn't work)

**Describe alternatives you've considered**

**Additional context**

**Comment by cboxdoerfer** [comment]
It seems the macOS glib backend doesn't implement the `launch_uris_async` interface yet. I don't have a macOS system to test it, so maybe you could try the following workaround:

What happens when we always use the `#else` branch in [this](https://github.com/cboxdoerfer/fsearch/blob/master/src/fsearch_file_utils.c#L299) conditional on macOS? In case you're not familiar with C, you just need the remove all the lines from [`#if GLIB_CHECK_VERSION(2, 60, 0)`](https://github.com/cboxdoerfer/fsearch/blob/master/src/fsearch_file_utils.c#L299) up to (and including) the [`#else`](https://github.com/cboxdoerfer/fsearch/blob/master/src/fsearch_file_utils.c#L307) line and also the single [`#endif`](https://github.com/cboxdoerfer/fsearch/blob/master/src/fsearch_file_utils.c#L316) line.

**Comment by DUOLabs333** [comment]
It worked (I'll just add a condition for MacOS) --- there's also the problem of file type images not showing, but I can fix that later. Do you want me to start a PR to accept this change along with some other compatibility fixes for MacOS?

**Comment by cboxdoerfer** [comment]
> Do you want me to start a PR to accept this change along with some other compatibility fixes for MacOS?

Sure that would be great.

**Comment by DUOLabs333** [comment]
#411
