### ISSUE TITLE
Search within files and into their metadata

### ISSUE THREAD

**Issue by lf-araujo** [cboxdoerfer/fsearch#45]
Search within a pdf, emails, docs, odts, and look into metadata of photos. Otherwise, what it does adds to Recoll?

**Comment by cboxdoerfer** [comment]
Content searching isn't a high priority  right now since I use other tools for that which work great for my needs and I don't think I could do it any better than grep, the silver searcher, recoll, tracker, baloo, etc. anyway.

All I'm going to do is probably something like the "content:" function in Everything. But that's not going to happen anytime soon.

**Comment by cboxdoerfer** [comment]
Duplicate of #17, closing.

**Comment by Wallby** [comment]
> Content searching isn't a high priority right now since I use other tools for that which work great for my needs and I don't think I could do it any better than grep, the silver searcher, recoll, tracker, baloo, etc. anyway.

Perhaps you could run grep (or FINDSTR on windows) on a list of files to not require a lot of implementation effort?
