### ISSUE TITLE
Wildcards? 

### ISSUE THREAD

**Issue by Swedland** [cboxdoerfer/fsearch#57]
I'm using Everything in Windows and now I can't figure it out how to find a folder (with FSearch) with for example 'Backup 160522'.  I remember '160522' so my search-string are **'*1605*'**. I should get as result folder and filenames that contain 1605 but....no. Isn't '*' and '?' used as wildcards in Linux/Fsearch?

Regards

**Comment by cboxdoerfer** [comment]
@Swedland, which version do you use, i.e. did you build FSearch from source or did you use the PPA, AUR target or the deb file?

Both `*` and `?` are supported wildcards and should work as expected in normal search mode. But also `1605` should match files or folders like `Backup 160522` without any wildcards:

![](http://i.imgur.com/06zrrs6.png)

Are you sure all the necessary folders are indexed?

**Comment by Swedland** [comment]
Thanks for the reply,
Yes, the HOME-folder are in the list.

I tested once again with "1605" and I got all Backup-folders with name "Backup 160522", "Backup 160525" and so on.  That feels ok but why didn't '*1605' working?  

When I tested the FSearch it was  installed the minute before but in the lower right corner it had the number of indexed files, 17300 items. 
Perhaps I never did test only '1605' without the astrix because I knew that it was a "Backup " infront of 1605? Still, I thought "*1605" should also find the folders and NOT only '1605'.

Happy to know more about this...

**Comment by cboxdoerfer** [comment]
>I tested once again with "1605" and I got all Backup-folders with name "`Backup 160522`", "Backup 160525" and so on. That feels ok but why didn't '*1605' working?

Because that's not how wildcards are working. `*1605` won't match `Backup 160522` in Everything Search either.

- `*1605` matches everything which ends with `1605`
- `1605*` matches everything which starts with `1605`
- `*1605*` matches everything which contains `1605'

So obviously with `*1605` you can't find `Backup 160522`, because it doesn't end with `1605` but with `160522`. You'd need to use `*1605*` or just `1605`.

If you don't use `*` at all the default search method is a sub string search, i.e. just typing `1605` is the same as `*1605*`. Both will match all files or folders which contain `1605`.
