### ISSUE TITLE
Window is not centered when size of window is set

### ISSUE THREAD

**Issue by rieje** [cboxdoerfer/fsearch#65]
On i3 window manager, if I pre-define the size of a floating window, it does not open in the center of the screen. What it seems to do is to re-use the position of the top left corner's window if the window's size was not pre-defined, then expand the dimensions from there on the bottom right corner to the dimensions of the pre-defined size. On all my other applications they open centered as expected even with a pre-defined size.

**Comment by cboxdoerfer** [comment]
Thanks for reporting. I'll have a look at that.

**Comment by cboxdoerfer** [comment]
I'm not sure how to reproduce that. Can you give some more details? Do you have an i3 rule to launch fsearch in floating mode?

**Comment by rieje** [comment]
I have the following relevant rules:
   for_window [instance="fsearch_floating"] floating enable
   bindsym $mod+Shift+bar exec --no-startup-id fsearch --name fsearch_floating

Here's a screenshot showing that it's not centered when launched.

**Comment by cboxdoerfer** [comment]
@rieje, I can reproduce that. Apparently this is caused by the setting `Remember window size`. If you disable it FSearch is properly centered even when `floating_minimum_size 1050 x 500` is set.

Do you have `Remember window size` enabled? And if so, what are the values of `window_width` and `window_height` in `~/.config/fsearch/fsearch.conf`?

**Comment by rieje** [comment]
Disabling `Remember window size` still doesn't center for me. My [settings](https://ptpb.pw/ACHge5IR0Tru27MGhVXJ8jtTER7t).

**Comment by cboxdoerfer** [comment]
You're right, my window was also not perfectly centered, it was a few pixels off. But I think I found the reason for this bug: FSearch window has a hint to be centered on creation, so GDK places it in the center at first, then i3 resizes the window according to `floating_minimum_size` which causes the window to be out of place.

The fix is simple and already on master: Don't tell GTK+ to center the window on creation, let the window manager handle that.
